language: python

python:
  - "3.6"
  - "3.7-dev"
  - "3.8"

services:
  - docker
  - redis

install:
  - pip install -r requirements.txt

# command to run tests
script:
  - ./manage.py makemigrations
  - ./manage.py migrate
  - ./manage.py test
  - coverage run --source='.' manage.py test
  - codecov
