language: python

python:
  - "3.8"

services:
  - mysql


install:
  - pip install -r requirements.txt

before_script:
  - mysql -e 'create database example;'
  - mysql -e 'create database test_example;'
  - mysql -e "CREATE USER 'example'@'localhost' IDENTIFIED BY 'example';"
# command to run tests
script:
  - bash scripts/init.sh
  - ./manage.py makemigrations
  - ./manage.py migrate
  - ./manage.py test
  - coverage run --source='.' manage.py test
  - codecov
