version: '3.9'
services:
  web:
   depends_on:
     - redis
  nginx:
   build:
    context: ./docker/nginx
    dockerfile: ./Dockerfile
    args:
      - NGINX_ENV=dev
   ports:
      - "80:80"

volumes:
  certbot-etc:
  certbot-var:
    