version: '3.9'
services:
  db:
    image: mysql:8.0.28
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - docker/db/.env

    expose:
      - 3306

  web:
    restart: always
    build: .
    command: "/bin/bash /una/start.sh"
    volumes:
      - ./:/una:rw
      - ./docker/nginx/www:/una/static
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
      args:
        - NGINX_ENV=prod
    volumes:
      - ./docker/nginx/www:/www:rw
    depends_on:
      - web
